### ISSUE TITLE
Passing data to registerHelper

### ISSUE THREAD

**Issue by karneaud** [Gottwik/Enduro#100]
I have the following in my content file

```
{
  title: "title",
  some: [...,...,...],
  another:[...,...,...,....],
....
```

and I have a registered helper as followers

```
enduro.templating_engine.registerHelper('breaklist', function () {
	var lists = [], list = arguments[0], items = list.length/ 2 ;
	while(list.length > 0) {
		if(list.length <= items) items = list.length;
		lists.push(list.splice(0, items));
	}
	console.log(arguments);
	return options.fn(lists);
```

and I'm using the helper via

```
{{#breaklist some as |items|}}
 {{#each items as |item|}}
 .........
```

I however note that it is passing the whole content object whereas I'm only trying to pass the "some" property a parameter

How do I pass only the property I want from the content file?

**Comment by karneaud** [comment]
Why does the function convert arrays into objects?

**Comment by Gottwik** [comment]
**Why is it passing whole context file?**
Because you are using block parameters(`as |something|`) and that gets passed into options or `arguments[1]`. arguments[0] will get the whole context as if you didn't pass anything. Does it make sense?

**Why is your array converted into an object**
Short answer is that arrays don't work well with enduro cultures, so it gets converted into object. **Still this is poor excuse and I'll try to fix this soon**, although I tried once and having arrays in enduro admin is challenging.

In the meantime you iterate it with `for (index in some) {` and I also suggest as best practice to use:

```
{
    title: "title",
    some: [
        {
            value: 1,
        },
        {
            value: 2,
        },
        {
            value: 3,
        },
    ],
}
```
