### ISSUE TITLE
CMS content files extension is incorrect.

### ISSUE THREAD

**Issue by chriseaton** [Gottwik/Enduro#14]
I'm using an IDE to manage my enduro project, and I noticed that the cms/ content files end with a ".js" file extension instead of ".json" - this causes my IDE to think the file is a JavaScript file and thinks there are parsing errors. 

*also at first glance it made me assume they were code files not data/content/config files.

**Comment by Gottwik** [comment]
I know exactly what you mean and you are right.  The context files are deliberately not json files, primarily because they are harder to write by hand.

I made a workaround with cf48670 that you now can add `module.exports = ` in front of the object definition. This should make your lint happy.

Funny enough, you can actually put functions in the context files:

```
{
  page_title: 'increase_demo',
  increase: function (count) {
    return count + 2
  }
}
```

and then use it as you would use a helper: `<p>Hey {{what 3}}</p>` will render `Hey 5`
