### ISSUE TITLE
Gitter? Slack? :D

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [Gottwik/Enduro#39]
Hey Gottwik, first of all I would like to **thank you for Enduro 🎉 ,** because a CMS for a static site is a really-really needed thing for bloggers, developers and simple users. Maybe enduro doesn't position itself as a static site constructor, but I was looking exactly for that use case. I believe Enduro will make site development more accessible and less tedious. Honestly, I was thinking about making such project for about 1-2 years, but had no spare time for it :c

Why not adding a gitter chat for this repo, or launching a slack community? Probably it will help enduro spread among people :)

Keep up doing great work! I hope I'll join you as a contributor soon :D

**Comment by Gottwik** [comment]
Hey @CosmoMyzrailGorynych you are very welcome to join the project. Thank you for the nice comments.

I like that enduro.js can generate static websites but it also has admin interface and you can build api or dynamic pages using the express app in app/app.js file. When I started this project I didn't have static page generator in mind. I thought it was just smart to pregenerate the html files so that each pageload is blazing fast.

Hey, good idea with the gitter - created a room. Maybe we can add slack if the gitter get some traction. If you had any _marketing_ ideas, let me know, I am definitely interested

**Comment by Pierrebleroux** [comment]
Hey @Gottwik, what is the link to the gitter room?

This project has really got my attention, it looks quite cool and I would also love to join as a contributor :)

**Comment by justindra** [comment]
Hi there,

Firstly @Gottwik Interesting project, have just found it and am thinking of using it for one of my projects. Will be playing around with it today.

Secondly, IMHO, I do not think Gitter as a community works too well, as things always seem to get lost and hard to keep track of different conversations. Slack I would say would be a better option.

**Comment by CosmoMyzrailGorynych** [comment]
In case someone is searching gitter chat and haven't found it yet, here it is: https://gitter.im/Enduro-js/Lobby
