### ISSUE TITLE
A few questions (i'm a relatively new developer)

### ISSUE THREAD

**Issue by Jonesatron** [Gottwik/Enduro#40]
Hi,

Love enduro,  its  great and just what I have been looking for as a CMS.

I'm having a couple of issues though. They might be amateur errors by be so I apologise for wasting time if they are.

I have hosted my site, copied all the files from _src, but the admin interface doesn't appear to be working when I go to www.mydomain.com/admin. Do I need to set anything extra up to get admin working.

Secondly, when I have gone back to my project today, I'm getting errors saying that partials could not be found although they are definately there. (Hopefully see screenshot) It was working perfectly yesterday.

![screen shot 2017-04-09 at 08 25 18](https://cloud.githubusercontent.com/assets/25160925/24835586/1a71933c-1cfe-11e7-922f-874522ae4ede.png)

Any help would be great. I've read the documentation but couldn't seem to find what I needed. Thank you in advance!

**Comment by Gottwik** [comment]
**No admin interface**

Well, there are two options when hosting enduro project. You can:

1. use enduro.js as server - this has admin interface, versioning and allows backend logic to be implemented such as api calls. This depends on having a server with computing power. Either your own server or using heroku or similar service.
2. use enduro.js as static page generator - this is how you are doing it right now. The problem with this is that there is no admin interface or anything functional on your server. Advantage is you can get free hosting on github, netlify because serving static files are easy and cheap.

Good news you can still use admin interface and keep this workflow, just not on a server. Run `enduro` on your localhost, you get an admin interface on `localhost:5000/admin` and after you are done just copy the files from _src.

What kind of server do you have? If it's your dedicated server you can just start enduro on the server by running `enduro start` and you get your admin interface as you expected.

**Missing partials**
You have the components in `pages/components`. For enduro to pick these partials/components you have to place them in `/components` folder. Just move the `/components` folder from pages to project's root folder.

Let me know if this solves your issues, I am happy to help.

**Comment by Jonesatron** [comment]
Thanks for your quick reply. I sorted the second problem. Must've dragged the folder into the pages folder by accident.

I currently use dreamboat to host my webpages but it's the back end admin functionality that i really want so i may need to look into something else if i can't use enduro on that.

What would you suggest as my best option?

Again thanks for going out your way to help a rookie!

Cheers,

Craig

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by Gottwik** [comment]
You basically need node.js to have the admin interface working. If you have the basic dreamboat shared hosting you can only run php. Wordpress is done in php, so that is your best option. There are ton of themes for wordpress it's mature, stable, well-documented and is used by possibly majority of websites.

However if you feel adventurous and want to learn something, or prefer to use javascript over php I suggest you give enduro a try. You can create a [free heroku instance](https://signup.heroku.com/) and when your site goes live you pay $7 per month.

**Comment by Jonesatron** [comment]
Cheers.

I'm adventurous and need to learn a lot more JavaScript for work so i will be going with enduro. It's allowed me to learn about handlebars too, as i have only used nunjucks before!

Thanks a lot for the help and i will check out heroku.

Cheers,

Craig

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by Pierrebleroux** [comment]
Another awesome place where you can host your static pages (_for free_) is http://surge.sh/.
I regularly use it for any static page - and have been recently experimenting with enduro.

Just run the "surge" command from the _src folder and it will work :)

**Comment by Jonesatron** [comment]
Cheers mate.

Got the project up and running on heroku and evennode. So that's awesome.

On heroku, how many websites would i be able to host for $7 a month? Would it just be one?

I'll check out that surge now.

Thanks again

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by Gottwik** [comment]
@Jonesatron it's $7 per project, you can mix two websites together as one enduro.js project. It's also free while you are developing it, which is helpful.

**Comment by Gottwik** [comment]
I am going ahead and close this issue. Happy to answer more hosting questions thought :-)
